M = 16;
 n = 100;
 snr = 20;
 data = randi([0 M-1], n, 1);
 mod_signal = qammod(data, M, 'UnitAveragePower', true);
 scatterplot(mod_signal);
 title('M-ary QAM Modulated Signal');
 figure;
 subplot(2,1,1);
 stem(real(mod_signal), 'o-');
 title('Real Part of M-ary QAM Modulated Signal');
 xlabel('Symbol Index');
 ylabel('Amplitude');
 subplot(2,1,2);
 stem(imag(mod_signal), 'o-');
 title('Imaginary Part of M-ary QAM Modulated Signal');
 xlabel('Symbol Index');
 ylabel('Amplitude');
 noisy_signal = awgn(mod_signal, snr, 'measured');
 figure;
 plot(noisy_signal);
 title('Noisy M-ary QAM Signal');
 demod_data = qamdemod(noisy_signal, M, 'UnitAveragePower', true);
 figure;
 stem(demod_data);
 title('Demodulated M-ary QAM Data');
 xlabel('Symbol Index');
 ylabel('Demodulated Value');