M = 16;
 n = 100;
 snr = 10;
 Fs = 1000;
 samplesPerSymbol = 8;
 data = randi([0 1], n, 1);
 mod_signal = mskmod(data, samplesPerSymbol);
 figure;
 scatterplot(mod_signal);
 title('MSK Modulated Signal (Scatter Plot)');
 figure;
 subplot(2,1,1);
 plot(real(mod_signal));
 title('Real Part of MSK Modulated Signal');
 xlabel('Sample Index');
 ylabel('Amplitude');
 subplot(2,1,2);
 plot(imag(mod_signal));
 title('Imaginary Part of MSK Modulated Signal');
 xlabel('Sample Index');
 ylabel('Amplitude');
 noisy_signal = awgn(mod_signal, snr, 'measured');
 figure;
 plot(noisy_signal);
 title('Noisy MSK Signal');
 xlabel('Sample Index');
 ylabel('Amplitude');
 demod_data = mskdemod(noisy_signal, samplesPerSymbol);
 figure;
 stem(demod_data);
 title('Demodulated MSK Data');
 xlabel('Bit Index');
 ylabel('Demodulated Value');
